version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgresql
    environment:
      POSTGRES_USER: doba
      POSTGRES_PASSWORD: dobadov3333
      POSTGRES_DB: postgresql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dobadov3333
      MYSQL_USER: doba
      MYSQL_PASSWORD: dobadov3333
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
  mongo:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: doba
      MONGO_INITDB_ROOT_PASSWORD: dobadov3333
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo/data:/data/db
  redis:
    image: redis:7
    container_name: redis
    environment:
      REDIS_PASSWORD: dobadov3333
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: doba
      RABBITMQ_DEFAULT_PASS: dobadov3333
    restart: always
    ports:
      - "5672:5672"
    volumes:
      - ./volumes/mq:/var/lib/rabbitmq
